---


# Instalação do Google Chrome

- name: Instalando o Google Chrome
  apt:
    name: google-chrome-stable
    state: present
    update_cache: yes
  become: true
  tags:
    - chrome
    - web


# Instalação do Opera

- name: Instalando o Opera
  apt:
    name: opera-stable
    state: present
    update_cache: yes
  become: true
  tags:
    - opera
    - web


# Instalação do Vivaldi

- name: Instalando o Vivaldi
  apt:
    name: vivaldi-stable
    state: present
    update_cache: yes
  become: true
  tags:
    - vivaldi
    - web
