---

# Adicionando o repositorio do Google Chrome

- name: Importando a chave do repositorio do Google Chrome
  rpm_key:
    key: https://dl.google.com/linux/linux_signing_key.pub
    state: present
  become: true
  tags:
    - repo
    - chrome
    - web

- name: Copiando arquivo de repositório do Google Chrome
  copy:
    src: google-chrome-rpm.repo
    dest: /etc/yum.repos.d/google-chrome.repo
    owner: root
    group: root
    mode: "0644"
  become: true
  tags:
    - repo
    - chrome
    - web


# Adicionando o repositorio do Opera

- name: Importando a chave do repositorio do Opera
  rpm_key:
    key: https://rpm.opera.com/rpmrepo.key
    state: present
  become: true

- name: Copiando arquivo de repositório do Opera
  copy:
    src: opera-rpm.repo
    dest: /etc/yum.repos.d/opera.repo
    owner: root
    group: root
    mode: "0644"
  become: true
  tags:
    - repo
    - opera
    - web

# Adicionando o repositorio do Vivaldi

- name: Importando a chave do repositorio do Vivaldi
  rpm_key:
    key: http://repo.vivaldi.com/archive/linux_signing_key.pub
    state: present
  become: true
  tags:
    - repo
    - vivaldi
    - web

- name: Copiando arquivo de repositório do Vivaldi
  copy:
    src: vivaldi-rpm.repo
    dest: /etc/yum.repos.d/vivaldi.repo
    owner: root
    group: root
    mode: "0644"
  become: true
  tags:
    - repo
    - vivaldi
    - web
